apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-monitor
subjects:
  - kind: ServiceAccount
    name: sa-pod
roleRef:
  kind: Role
  name: role-pod
  apiGroup: rbac.authorization.k8s.io
